// Auto-generated offset constants for Go go1.26.7
// Generated by scripts/generate_go_bindings.py
// Target: linux/amd64
//
// DO NOT EDIT - regenerate with:
//   python3 scripts/generate_go_bindings.py go1.26.7

// runtime.bucket
pub const BUCKET_SIZE: usize = 48;
pub const BUCKET_ALLNEXT: usize = 8;
pub const BUCKET_TYP: usize = 16;
pub const BUCKET_NSTK: usize = 40;

// runtime.memRecord
pub const MEM_RECORD_SIZE: usize = 128;
pub const MEM_RECORD_ACTIVE: usize = 0;
pub const MEM_RECORD_FUTURE: usize = 32;
pub const MEM_RECORD_FUTURE_CYCLES: usize = 3;

// runtime.memRecordCycle
pub const MEM_RECORD_CYCLE_SIZE: usize = 32;
pub const MEM_RECORD_CYCLE_ALLOCS: usize = 0;
pub const MEM_RECORD_CYCLE_FREES: usize = 8;
pub const MEM_RECORD_CYCLE_ALLOC_BYTES: usize = 16;
pub const MEM_RECORD_CYCLE_FREE_BYTES: usize = 24;

// runtime.blockRecord
pub const BLOCK_RECORD_SIZE: usize = 16;
pub const BLOCK_RECORD_COUNT: usize = 0;
pub const BLOCK_RECORD_CYCLES: usize = 8;

// runtime.ticksType
pub const TICKS_START_TICKS: usize = 8;
pub const TICKS_START_TIME: usize = 16;
pub const TICKS_VAL: usize = 24;

// runtime.g
pub const G_SIZE: usize = 456;
pub const G_STACK_HI: usize = 8;
pub const G_SCHED_PC: usize = 64;
pub const G_SCHED_BP: usize = 96;
pub const G_SYSCALLPC: usize = 112;
pub const G_SYSCALLBP: usize = 120;
pub const G_ATOMICSTATUS: usize = 144;
pub const G_GOID: usize = 152;
pub const G_WAITSINCE: usize = 168;
pub const G_WAITREASON: usize = 176;
pub const G_STARTPC: usize = 304;
pub const G_LABELS: usize = 352;

// runtime/pprof.labelMap
pub const LABEL_MAP_LIST: usize = 0;

// internal/runtime/pprof/label.Label
pub const LABEL_SIZE: usize = 32;
pub const LABEL_KEY: usize = 0;
pub const LABEL_VALUE: usize = 16;

// runtime/trace.traceMultiplexer
pub const TRACE_MUX_FLIGHT_RECORDER: usize = 48;

// runtime/trace.recorder
pub const TRACE_RECORDER_R: usize = 0;

// runtime/trace.FlightRecorder
pub const FLIGHT_RECORDER_HEADER: usize = 16;
pub const FLIGHT_RECORDER_RING: usize = 88;

// runtime/trace.rawGeneration
pub const RAW_GENERATION_SIZE: usize = 48;
pub const RAW_GENERATION_GEN: usize = 0;
pub const RAW_GENERATION_BATCHES: usize = 24;

// Constants
pub const MEM_PROFILE: u64 = 1; // runtime.memProfile
pub const BLOCK_PROFILE: u64 = 2; // runtime.blockProfile
pub const MUTEX_PROFILE: u64 = 3; // runtime.mutexProfile
pub const G_RUNNING: u32 = 2; // runtime._Grunning
pub const G_SYSCALL: u32 = 3; // runtime._Gsyscall
pub const G_DEAD: u32 = 6; // runtime._Gdead
pub const G_DEADEXTRA: u32 = 11; // runtime._Gdeadextra
pub const G_SCAN: u32 = 4096; // runtime._Gscan

// internal/trace/tracev2
pub const EV_EVENT_BATCH: u8 = 1; // EvEventBatch
pub const EV_EXPERIMENTAL_BATCH: u8 = 49; // EvExperimentalBatch
pub const EV_END_OF_GENERATION: u8 = 52; // EvEndOfGeneration

// runtime.gStatusStrings
pub const G_STATUS_NAMES: [&str; 12] = [
    "idle",
    "runnable",
    "running",
    "syscall",
    "waiting",
    "",
    "dead",
    "",
    "copystack",
    "preempted",
    "leaked",
    "waiting for cgo callback",
];

// runtime.waitReasonStrings
pub const WAIT_REASONS: [&str; 47] = [
    "",
    "GC assist marking",
    "IO wait",
    "dumping heap",
    "garbage collection",
    "garbage collection scan",
    "panicwait",
    "GC assist wait",
    "GC sweep wait",
    "GC scavenge wait",
    "finalizer wait",
    "force gc (idle)",
    "GOMAXPROCS updater (idle)",
    "semacquire",
    "sleep",
    "chan receive (nil chan)",
    "chan send (nil chan)",
    "select (no cases)",
    "select",
    "chan receive",
    "chan send",
    "sync.Cond.Wait",
    "sync.Mutex.Lock",
    "sync.RWMutex.RLock",
    "sync.RWMutex.Lock",
    "sync.WaitGroup.Wait",
    "trace reader (blocked)",
    "wait for GC cycle",
    "GC worker (idle)",
    "GC worker (active)",
    "preempted",
    "debug call",
    "GC mark termination",
    "stopping the world",
    "flushing proc caches",
    "trace goroutine status",
    "trace proc status",
    "page trace flush",
    "coroutine",
    "GC weak to strong wait",
    "synctest.Run",
    "synctest.Wait",
    "chan receive (durable)",
    "chan send (durable)",
    "select (durable)",
    "sync.WaitGroup.Wait (durable)",
    "cleanup wait",
];
