// Auto-generated offset constants for CPython v3.11.0
// Generated by scripts/generate_python_bindings.py
// Target: x86_64-unknown-linux-gnu
//
// DO NOT EDIT - regenerate with:
//   python3 scripts/generate_python_bindings.py --cpython <path> v3.11.0

// PyObject
pub const PY_OBJECT_OB_TYPE: usize = 8;

// PyTypeObject
pub const PY_TYPE_OBJECT_TP_NAME: usize = 24;

// PyVarObject
pub const PY_VAR_OBJECT_OB_SIZE: usize = 16;

// PyASCIIObject
pub const PY_ASCII_OBJECT_SIZE: usize = 48;

// PyTupleObject
pub const PY_TUPLE_OBJECT_OB_ITEM: usize = 24;

// PyBytesObject
pub const PY_BYTES_OBJECT_OB_SVAL: usize = 32;

// PyThreadState
pub const PY_THREAD_STATE_CFRAME: usize = 56;
pub const PY_THREAD_STATE_THREAD: usize = 152;

// _PyCFrame
pub const PY_CFRAME_CURRENT_FRAME: usize = 8;

// _PyInterpreterFrame
pub const PY_INTERP_FRAME_CODE: usize = 32;
pub const PY_INTERP_FRAME_PREVIOUS: usize = 48;
pub const PY_INTERP_FRAME_LOCALSPLUS: usize = 72;
pub const PY_INTERP_FRAME_PREV_INSTR: usize = 56;

// PyCodeObject
pub const PY_CODE_OBJECT_CO_FLAGS: usize = 48;
pub const PY_CODE_OBJECT_CO_FILENAME: usize = 112;
pub const PY_CODE_OBJECT_CO_NAME: usize = 120;
pub const PY_CODE_OBJECT_CO_QUALNAME: usize = 128;
pub const PY_CODE_OBJECT_CO_LINETABLE: usize = 136;
pub const PY_CODE_OBJECT_CO_FIRSTLINENO: usize = 72;

// _PyRuntimeState / PyInterpreterState compound offsets
pub const PYRUNTIME_TLS_KEY_OFFSET: usize = 596;
pub const PYRUNTIME_TSTATE_CURRENT_OFFSET: usize = 576;
pub const PYRUNTIME_GIL_LOCKED_OFFSET: usize = 376;
pub const PYRUNTIME_GIL_LAST_HOLDER_OFFSET: usize = 368;
