// Auto-generated offset constants for CPython v3.10.0
// Generated by scripts/generate_python_bindings.py
// Target: x86_64-unknown-linux-gnu
//
// DO NOT EDIT - regenerate with:
//   python3 scripts/generate_python_bindings.py --cpython <path> v3.10.0

// PyObject
pub const PY_OBJECT_OB_TYPE: usize = 8;

// PyTypeObject
pub const PY_TYPE_OBJECT_TP_NAME: usize = 24;

// PyVarObject
pub const PY_VAR_OBJECT_OB_SIZE: usize = 16;

// PyASCIIObject
pub const PY_ASCII_OBJECT_SIZE: usize = 48;

// PyTupleObject
pub const PY_TUPLE_OBJECT_OB_ITEM: usize = 24;

// PyBytesObject
pub const PY_BYTES_OBJECT_OB_SVAL: usize = 32;

// PyThreadState
pub const PY_THREAD_STATE_FRAME: usize = 24;
pub const PY_THREAD_STATE_THREAD: usize = 176;
pub const PY_THREAD_STATE_INTERP: usize = 16;

// PyFrameObject (via _frame)
pub const PY_FRAME_OBJECT_BACK: usize = 24;
pub const PY_FRAME_OBJECT_CODE: usize = 32;
pub const PY_FRAME_OBJECT_LASTI: usize = 96;
pub const PY_FRAME_OBJECT_LOCALSPLUS: usize = 352;
pub const PY_FRAME_OBJECT_GEN: usize = 88;

// PyCodeObject
pub const PY_CODE_OBJECT_CO_FLAGS: usize = 36;
pub const PY_CODE_OBJECT_CO_FILENAME: usize = 104;
pub const PY_CODE_OBJECT_CO_NAME: usize = 112;
pub const PY_CODE_OBJECT_CO_VARNAMES: usize = 72;
pub const PY_CODE_OBJECT_CO_FIRSTLINENO: usize = 40;
pub const PY_CODE_OBJECT_CO_LINETABLE: usize = 120;

// _PyRuntimeState / PyInterpreterState compound offsets
pub const PYRUNTIME_TLS_KEY_OFFSET: usize = 588;
pub const PYRUNTIME_TSTATE_CURRENT_OFFSET: usize = 568;
pub const PYRUNTIME_GIL_LOCKED_OFFSET: usize = 368;
pub const PYRUNTIME_GIL_LAST_HOLDER_OFFSET: usize = 360;
pub const PYINTERP_MODULES_OFFSET: usize = 856;
