// Auto-generated offset constants for CPython v3.13.0
// Generated by scripts/generate_python_bindings.py
// Target: x86_64-unknown-linux-gnu
//
// DO NOT EDIT - regenerate with:
//   python3 scripts/generate_python_bindings.py --cpython <path> v3.13.0

// PyObject
pub const PY_OBJECT_OB_TYPE: usize = 8;

// PyTypeObject
pub const PY_TYPE_OBJECT_TP_NAME: usize = 24;

// PyVarObject
pub const PY_VAR_OBJECT_OB_SIZE: usize = 16;

// PyASCIIObject
pub const PY_ASCII_OBJECT_SIZE: usize = 40;

// PyTupleObject
pub const PY_TUPLE_OBJECT_OB_ITEM: usize = 24;

// PyBytesObject
pub const PY_BYTES_OBJECT_OB_SVAL: usize = 32;

// PyThreadState (3.13: current_frame directly on _ts, no _PyCFrame)
pub const PY_THREAD_STATE_CURRENT_FRAME: usize = 72;
pub const PY_THREAD_STATE_THREAD: usize = 152;
pub const PY_THREAD_STATE_INTERP: usize = 16;

// _PyInterpreterFrame (f_code renamed to f_executable, prev_instr to instr_ptr)
pub const PY_INTERP_FRAME_CODE: usize = 0;
pub const PY_INTERP_FRAME_PREVIOUS: usize = 8;
pub const PY_INTERP_FRAME_LOCALSPLUS: usize = 72;
pub const PY_INTERP_FRAME_PREV_INSTR: usize = 56;
pub const PY_INTERP_FRAME_OWNER: usize = 70;

// PyCodeObject
pub const PY_CODE_OBJECT_CO_FLAGS: usize = 48;
pub const PY_CODE_OBJECT_CO_FILENAME: usize = 112;
pub const PY_CODE_OBJECT_CO_NAME: usize = 120;
pub const PY_CODE_OBJECT_CO_QUALNAME: usize = 128;
pub const PY_CODE_OBJECT_CO_LINETABLE: usize = 136;
pub const PY_CODE_OBJECT_CO_FIRSTLINENO: usize = 68;
pub const PY_CODE_OBJECT_CO_CODE_ADAPTIVE: usize = 200;

// PyCoroObject / PyGenObject
pub const PY_CORO_OBJECT_CR_ORIGIN_OR_FINALIZER: usize = 56;
pub const PY_GEN_OBJECT_GI_IFRAME: usize = 72;

// _PyRuntimeState / PyInterpreterState compound offsets
pub const PYRUNTIME_TLS_KEY_OFFSET: usize = 2164;
pub const PYRUNTIME_INTERPRETERS_HEAD_OFFSET: usize = 632;
pub const PYINTERP_MODULES_OFFSET: usize = 7656;
pub const PYINTERP_GIL_LOCKED_OFFSET: usize = 7768;
pub const PYINTERP_GIL_LAST_HOLDER_OFFSET: usize = 7760;
