// Auto-generated offset constants for CPython v3.14.7 (free-threaded)
// Generated by scripts/generate_python_bindings.py
// Target: x86_64-unknown-linux-gnu
//
// DO NOT EDIT - regenerate with:
//   python3 scripts/generate_python_bindings.py --installed <prefix> --free-threaded v3.14.7

// PyObject
pub const PY_OBJECT_OB_TYPE: usize = 24;
pub const PY_OBJECT_MANAGED_DICT_BEFORE: usize = 8;

// PyTypeObject
pub const PY_TYPE_OBJECT_TP_NAME: usize = 40;
pub const PY_TYPE_OBJECT_TP_BASICSIZE: usize = 48;
pub const PY_TYPE_OBJECT_TP_FLAGS: usize = 184;
pub const PY_TYPE_OBJECT_TP_DICTOFFSET: usize = 304;

// PyVarObject
pub const PY_VAR_OBJECT_OB_SIZE: usize = 32;

// PyASCIIObject
pub const PY_ASCII_OBJECT_SIZE: usize = 56;
pub const PY_ASCII_OBJECT_LENGTH: usize = 32;
pub const PY_ASCII_OBJECT_STATE: usize = 48;

// PyCompactUnicodeObject
pub const PY_COMPACT_UNICODE_OBJECT_SIZE: usize = 72;

// PyHeapTypeObject
pub const PY_HEAP_TYPE_OBJECT_HT_CACHED_KEYS: usize = 896;

// PyLongObject
pub const PY_LONG_OBJECT_LV_TAG: usize = 32;
pub const PY_LONG_OBJECT_OB_DIGIT: usize = 40;

// PyModuleObject
pub const PY_MODULE_OBJECT_MD_DICT: usize = 32;

// PyDictObject, PyDictKeysObject, its entries, PyDictValues
pub const PY_DICT_OBJECT_MA_USED: usize = 32;
pub const PY_DICT_OBJECT_MA_KEYS: usize = 48;
pub const PY_DICT_OBJECT_MA_VALUES: usize = 56;
pub const PY_DICT_KEYS_DK_LOG2_INDEX_BYTES: usize = 9;
pub const PY_DICT_KEYS_DK_KIND: usize = 10;
pub const PY_DICT_KEYS_DK_NENTRIES: usize = 24;
pub const PY_DICT_KEYS_DK_INDICES: usize = 32;
pub const PY_DICT_KEY_ENTRY_SIZE: usize = 24;
pub const PY_DICT_KEY_ENTRY_ME_KEY: usize = 8;
pub const PY_DICT_KEY_ENTRY_ME_VALUE: usize = 16;
pub const PY_DICT_UNICODE_ENTRY_SIZE: usize = 16;
pub const PY_DICT_UNICODE_ENTRY_ME_KEY: usize = 0;
pub const PY_DICT_UNICODE_ENTRY_ME_VALUE: usize = 8;
pub const PY_DICT_VALUES_VALID: usize = 3;
pub const PY_DICT_VALUES_VALUES: usize = 8;

// _Py_DebugOffsets
pub const PY_DEBUG_OFFSETS_COOKIE: usize = 0;
pub const PY_DEBUG_OFFSETS_VERSION: usize = 8;
pub const PY_DEBUG_OFFSETS_FREE_THREADED: usize = 16;
pub const PY_DEBUG_OFFSETS_RUNTIME_INTERPRETERS_HEAD: usize = 40;
pub const PY_DEBUG_OFFSETS_INTERP_IMPORTS_MODULES: usize = 96;

// PyTupleObject
pub const PY_TUPLE_OBJECT_OB_ITEM: usize = 48;

// PyBytesObject
pub const PY_BYTES_OBJECT_OB_SVAL: usize = 48;

// PyThreadState
pub const PY_THREAD_STATE_INTERP: usize = 16;
pub const PY_THREAD_STATE_CURRENT_FRAME: usize = 72;
pub const PY_THREAD_STATE_THREAD: usize = 152;

// _PyInterpreterFrame
pub const PY_INTERP_FRAME_CODE: usize = 0;
pub const PY_INTERP_FRAME_PREVIOUS: usize = 8;
pub const PY_INTERP_FRAME_LOCALSPLUS: usize = 80;
pub const PY_INTERP_FRAME_PREV_INSTR: usize = 56;
pub const PY_INTERP_FRAME_OWNER: usize = 78;

// PyCodeObject
pub const PY_CODE_OBJECT_CO_FLAGS: usize = 64;
pub const PY_CODE_OBJECT_CO_FILENAME: usize = 128;
pub const PY_CODE_OBJECT_CO_NAME: usize = 136;
pub const PY_CODE_OBJECT_CO_FIRSTLINENO: usize = 84;
pub const PY_CODE_OBJECT_CO_LINETABLE: usize = 152;
pub const PY_CODE_OBJECT_CO_QUALNAME: usize = 144;
pub const PY_CODE_OBJECT_CO_CODE_ADAPTIVE: usize = 232;

// PyCoroObject / PyGenObject
pub const PY_CORO_OBJECT_CR_ORIGIN_OR_FINALIZER: usize = 72;
pub const PY_GEN_OBJECT_GI_IFRAME: usize = 88;

// _PyRuntimeState / PyInterpreterState compound offsets
pub const PYRUNTIME_DEBUG_OFFSETS_OFFSET: usize = 0;
pub const PYRUNTIME_TLS_KEY_OFFSET: usize = 2340;
pub const PYRUNTIME_INTERPRETERS_HEAD_OFFSET: usize = 808;
pub const PYRUNTIME_INTERPRETERS_MAIN_OFFSET: usize = 816;
pub const PYINTERP_MODULES_OFFSET: usize = 7712;
pub const PYINTERP_GIL_LOCKED_OFFSET: usize = 7832;
pub const PYINTERP_GIL_LAST_HOLDER_OFFSET: usize = 7824;
